### ISSUE TITLE
Question: How to setup phpmyadmin

### ISSUE THREAD

**Issue by Kikketer** [mzazon/php-apache-mysql-containerized#17]
For some reason this whole Docker thing isn't setting in for me, their docs seem to be all over and it's hard to know what docker does vs the individual packages.  I'm simply attempting to setup a server locally to develop on (not be a docker expert).

So far your tutorial and this repo has really gotten me past the annoying obstacles of just setting up an environment so thank you.

But now I need to glance and explore the database itself, so I turned to "phpmyadmin" to see if that would work (I'd be game to try a desktop application too, but not sure if the database is accessible due to the "backend" network).

This is what I've done so far to the `docker-compose.yml` file:
```
  phpmyadmin:
    image: phpmyadmin:fpm-alpine
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:80
    networks:
      - frontend
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 10M
```

The attempt at least in my head is that this uses the `PMA_HOST` to connect to the `//mysql` domain and the 3306 port.  This configuration errors because the port 8080 is already in use (apache?).  I'm not sure how I would alter the port that phpmyadmin uses to then alter: `8081:3001` (3001 being the external port that I'd hit on my machine `localhost:3001`.

Is there something I'm missing?  Do you have any suggested docs I should look at?

**Comment by Kikketer** [comment]
Does this happen to you?
You ask a question after spending an hour trying to figure it out.  Then minutes after you ask, you figure it out? :)

For anyone that asks the same thing, this is what worked for me.  And connecting to `localhost:8081` brought up the site properly.

```
  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - 8081:80
    networks:
      - frontend
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 10M
```
